"""empty message

Revision ID: 0f3f77989a1a
Revises: 9e0e0c1ea78b
Create Date: 2020-09-28 15:40:09.452588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f3f77989a1a'
down_revision = '9e0e0c1ea78b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_context_example',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seed_example_id', sa.Integer(), nullable=False),
    sa.Column('context', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['seed_example_id'], ['seed_example.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('new_question_example',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seed_example_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['seed_example_id'], ['seed_example.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('new_question_example')
    op.drop_table('new_context_example')
    # ### end Alembic commands ###
