"""empty message

Revision ID: 1fe4834663a0
Revises: d55eab15a734
Create Date: 2020-09-28 14:14:49.920240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe4834663a0'
down_revision = 'd55eab15a734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seed_example',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('answer_a', sa.String(), nullable=True),
    sa.Column('answer_b', sa.String(), nullable=True),
    sa.Column('answer_c', sa.String(), nullable=True),
    sa.Column('correct_answer', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('example')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('context', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('answer_a', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('answer_b', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('answer_c', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('correct_answer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='example_pkey')
    )
    op.drop_table('seed_example')
    # ### end Alembic commands ###
