"""empty message

Revision ID: 9e0e0c1ea78b
Revises: 10101c2e690a
Create Date: 2020-09-28 14:28:21.643558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0e0c1ea78b'
down_revision = '10101c2e690a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('new_question_example')
    op.drop_table('new_context_example')
    op.add_column('seed_example', sa.Column('correct_answer_index', sa.String(), nullable=True))
    op.drop_column('seed_example', 'correct_answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seed_example', sa.Column('correct_answer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('seed_example', 'correct_answer_index')
    op.create_table('new_context_example',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seed_example_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('context', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['seed_example_id'], ['seed_example.id'], name='new_context_example_seed_example_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='new_context_example_pkey')
    )
    op.create_table('new_question_example',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seed_example_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['seed_example_id'], ['seed_example.id'], name='new_question_example_seed_example_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='new_question_example_pkey')
    )
    # ### end Alembic commands ###
